version: '3.0'

services:
  # client
  app:
    image: todo-app-image
    container_name: todo-app
    build: .
    tty: true
    stdin_open: true
    env_file:
      - .env.local
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - .:/usr/src/app
